name: "Manual approval"

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: Environment
        required: true
        type: choice
        options:
          - development
          - production
      nonce:
        description: Match token
        required: true
        type: string

run-name: "Approve ${{ inputs.env_name }} ${{ inputs.nonce }}"

permissions:
  contents: read

jobs:
  approve:
    uses: ./.github/workflows/reusable-approve.yml
    with:
      env_name: ${{ inputs.env_name }}
