name: "Template: Terraform Plan & Apply"

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      tf_folder:
        required: true
        type: string
      working_dir:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true

env:
  AWS_REGION: eu-west-1
  TF_VERSION: "1.11.4"

jobs:
  plan:
    name: "Plan"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency:
      group: tf-${{ inputs.working_dir }}-${{ inputs.env_name }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: Terraform Init
        env:
          TF_FOLDER: ${{ inputs.tf_folder }}
        run: terraform init -backend-config=config/$TF_FOLDER/config.remote
        working-directory: ${{ inputs.working_dir }}
      - name: Terraform Plan
        env:
          TF_FOLDER: ${{ inputs.tf_folder }}
        run: |
          terraform plan \
            -var-file=config/$TF_FOLDER/config.tfvars \
            -out=tfplan \
            -no-color
        working-directory: ${{ inputs.working_dir }}
      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ inputs.tf_folder }}-${{ inputs.env_name }}-${{ github.run_id }}
          path: ${{ inputs.working_dir }}/tfplan
          if-no-files-found: error
          retention-days: 5

  apply:
    name: "Apply"
    needs: plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency:
      group: tf-${{ inputs.working_dir }}-${{ inputs.env_name }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ inputs.tf_folder }}-${{ inputs.env_name }}-${{ github.run_id }}
          path: ${{ inputs.working_dir }}
      - name: Terraform Init
        env:
          TF_FOLDER: ${{ inputs.tf_folder }}
        run: terraform init -backend-config=config/$TF_FOLDER/config.remote
        working-directory: ${{ inputs.working_dir }}
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color tfplan
        working-directory: ${{ inputs.working_dir }}
