name: "Template: Terraform Plan & Apply Portal"

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      tf_folder:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true

env:
  AWS_REGION: eu-west-1
  TF_VERSION: "1.11.4"
  TF_WORKING_DIR: infra/portal

jobs:
  deploy:
    name: "Plan and apply"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    timeout-minutes: 70
    concurrency:
      group: tf-infra/portal-${{ inputs.env_name }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - id: session
        run: echo "started=$(date +%s)" >> "$GITHUB_OUTPUT"
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: Terraform Init
        env:
          TF_FOLDER: ${{ inputs.tf_folder }}
        run: terraform init -backend-config=config/$TF_FOLDER/config.remote
        working-directory: ${{ env.TF_WORKING_DIR }}
      - name: Terraform Plan
        env:
          TF_FOLDER: ${{ inputs.tf_folder }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          terraform plan \
            -var-file=config/$TF_FOLDER/config.tfvars \
            -out=tfplan \
            -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}
      - name: Wait for approval
        uses: ./.github/actions/wait-for-approval
        with:
          env_name: ${{ inputs.env_name }}
          github_token: ${{ github.token }}
          session_started: ${{ steps.session.outputs.started }}
      - name: Terraform Apply
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: terraform apply -auto-approve -no-color tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
